repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.6
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format
# run tests
- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: uv run pytest
    language: system
    types: [python]
    pass_filenames: false
    stages: [push]