# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import dataclasses
import datetime
from typing import Optional


@dataclasses.dataclass()
class BackfillStatus:
    hotspot_id: str
    year: int
    completed_at: datetime.datetime
    species_count: int


@dataclasses.dataclass()
class HotspotAllTimeSpecy:
    hotspot_id: str
    species_code: str


@dataclasses.dataclass()
class HotspotYearSpecy:
    hotspot_id: str
    year: int
    species_code: str
    common_name: str
    scientific_name: str
    first_obs_date: datetime.date
    observer_name: str
    checklist_id: str
    created_at: datetime.datetime


@dataclasses.dataclass()
class PendingProvisionalLifer:
    hotspot_id: str
    species_code: str
    common_name: str
    scientific_name: str
    obs_date: datetime.date
    observer_name: str
    sub_id: str
    lifer_type: str
    year: Optional[int]
    created_at: datetime.datetime
