# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import datetime
import pydantic
from typing import Optional


class BackfillStatus(pydantic.BaseModel):
    hotspot_id: str
    year: int
    completed_at: datetime.datetime
    species_count: int


class BirdcastPostLog(pydantic.BaseModel):
    location: str
    forecast_date: datetime.date
    posted_at: datetime.datetime


class HotspotAllTimeSpecy(pydantic.BaseModel):
    hotspot_id: str
    species_code: str


class HotspotYearSpecy(pydantic.BaseModel):
    hotspot_id: str
    year: int
    species_code: str
    common_name: str
    scientific_name: str
    first_obs_date: datetime.date
    observer_name: str
    checklist_id: str
    created_at: datetime.datetime


class PendingProvisionalLifer(pydantic.BaseModel):
    hotspot_id: str
    species_code: str
    common_name: str
    scientific_name: str
    obs_date: datetime.date
    observer_name: str
    sub_id: str
    lifer_type: str
    year: Optional[int]
    created_at: datetime.datetime


class RareBirdAlert(pydantic.BaseModel):
    species_code: str
    region_code: str
    common_name: str
    aba_code: int
    obs_date: datetime.date
    observer_name: str
    sub_id: str
    location_name: str
    alerted_at: datetime.datetime
