# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: queries.sql
import dataclasses
import datetime
from typing import AsyncIterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from cloaca.piper.db import models


GET_ALL_TIME_TOTAL = """-- name: get_all_time_total \\:one
SELECT COUNT(*) FROM hotspot_all_time_species
WHERE hotspot_id = :p1
"""


GET_KNOWN_ALL_TIME_SPECIES = """-- name: get_known_all_time_species \\:many
SELECT species_code FROM hotspot_all_time_species
WHERE hotspot_id = :p1
"""


GET_KNOWN_SPECIES = """-- name: get_known_species \\:many
SELECT species_code FROM hotspot_year_species
WHERE hotspot_id = :p1 AND year = :p2
"""


GET_PENDING_PROVISIONALS = """-- name: get_pending_provisionals \\:many
SELECT hotspot_id, species_code, common_name, scientific_name,
       obs_date, observer_name, sub_id, lifer_type, year, created_at
FROM pending_provisional_lifers
WHERE hotspot_id = :p1
"""


GET_YEAR_TOTAL = """-- name: get_year_total \\:one
SELECT COUNT(*) FROM hotspot_year_species
WHERE hotspot_id = :p1 AND year = :p2
"""


INSERT_ALL_TIME_SPECIES = """-- name: insert_all_time_species \\:exec
INSERT INTO hotspot_all_time_species (hotspot_id, species_code)
VALUES (:p1, :p2)
ON CONFLICT DO NOTHING
"""


INSERT_PENDING_PROVISIONAL = """-- name: insert_pending_provisional \\:exec
INSERT INTO pending_provisional_lifers
    (hotspot_id, species_code, common_name, scientific_name,
     obs_date, observer_name, sub_id, lifer_type, year)
VALUES (:p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, :p9)
ON CONFLICT DO NOTHING
"""


@dataclasses.dataclass()
class InsertPendingProvisionalParams:
    hotspot_id: str
    species_code: str
    common_name: str
    scientific_name: str
    obs_date: datetime.date
    observer_name: str
    sub_id: str
    lifer_type: str
    year: Optional[int]


INSERT_SPECIES = """-- name: insert_species \\:exec
INSERT INTO hotspot_year_species
    (hotspot_id, year, species_code, common_name, scientific_name,
     first_obs_date, observer_name, checklist_id)
VALUES (:p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8)
ON CONFLICT DO NOTHING
"""


@dataclasses.dataclass()
class InsertSpeciesParams:
    hotspot_id: str
    year: int
    species_code: str
    common_name: str
    scientific_name: str
    first_obs_date: datetime.date
    observer_name: str
    checklist_id: str


IS_BACKFILL_COMPLETE = """-- name: is_backfill_complete \\:one
SELECT 1 FROM backfill_status
WHERE hotspot_id = :p1 AND year = :p2
"""


MARK_BACKFILL_COMPLETE = """-- name: mark_backfill_complete \\:exec
INSERT INTO backfill_status (hotspot_id, year, completed_at, species_count)
VALUES (:p1, :p2, CURRENT_TIMESTAMP, :p3)
ON CONFLICT DO NOTHING
"""


REMOVE_ALL_TIME_SPECIES = """-- name: remove_all_time_species \\:exec
DELETE FROM hotspot_all_time_species
WHERE hotspot_id = :p1 AND species_code = :p2
"""


REMOVE_PENDING_PROVISIONAL = """-- name: remove_pending_provisional \\:exec
DELETE FROM pending_provisional_lifers
WHERE hotspot_id = :p1 AND species_code = :p2 AND lifer_type = :p3
"""


REMOVE_YEAR_SPECIES = """-- name: remove_year_species \\:exec
DELETE FROM hotspot_year_species
WHERE hotspot_id = :p1 AND year = :p2 AND species_code = :p3
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def get_all_time_total(self, *, hotspot_id: str) -> Optional[int]:
        row = (
            await self._conn.execute(
                sqlalchemy.text(GET_ALL_TIME_TOTAL), {"p1": hotspot_id}
            )
        ).first()
        if row is None:
            return None
        return row[0]

    async def get_known_all_time_species(
        self, *, hotspot_id: str
    ) -> AsyncIterator[str]:
        result = await self._conn.stream(
            sqlalchemy.text(GET_KNOWN_ALL_TIME_SPECIES), {"p1": hotspot_id}
        )
        async for row in result:
            yield row[0]

    async def get_known_species(
        self, *, hotspot_id: str, year: int
    ) -> AsyncIterator[str]:
        result = await self._conn.stream(
            sqlalchemy.text(GET_KNOWN_SPECIES), {"p1": hotspot_id, "p2": year}
        )
        async for row in result:
            yield row[0]

    async def get_pending_provisionals(
        self, *, hotspot_id: str
    ) -> AsyncIterator[models.PendingProvisionalLifer]:
        result = await self._conn.stream(
            sqlalchemy.text(GET_PENDING_PROVISIONALS), {"p1": hotspot_id}
        )
        async for row in result:
            yield models.PendingProvisionalLifer(
                hotspot_id=row[0],
                species_code=row[1],
                common_name=row[2],
                scientific_name=row[3],
                obs_date=row[4],
                observer_name=row[5],
                sub_id=row[6],
                lifer_type=row[7],
                year=row[8],
                created_at=row[9],
            )

    async def get_year_total(self, *, hotspot_id: str, year: int) -> Optional[int]:
        row = (
            await self._conn.execute(
                sqlalchemy.text(GET_YEAR_TOTAL), {"p1": hotspot_id, "p2": year}
            )
        ).first()
        if row is None:
            return None
        return row[0]

    async def insert_all_time_species(
        self, *, hotspot_id: str, species_code: str
    ) -> None:
        await self._conn.execute(
            sqlalchemy.text(INSERT_ALL_TIME_SPECIES),
            {"p1": hotspot_id, "p2": species_code},
        )

    async def insert_pending_provisional(
        self, arg: InsertPendingProvisionalParams
    ) -> None:
        await self._conn.execute(
            sqlalchemy.text(INSERT_PENDING_PROVISIONAL),
            {
                "p1": arg.hotspot_id,
                "p2": arg.species_code,
                "p3": arg.common_name,
                "p4": arg.scientific_name,
                "p5": arg.obs_date,
                "p6": arg.observer_name,
                "p7": arg.sub_id,
                "p8": arg.lifer_type,
                "p9": arg.year,
            },
        )

    async def insert_species(self, arg: InsertSpeciesParams) -> None:
        await self._conn.execute(
            sqlalchemy.text(INSERT_SPECIES),
            {
                "p1": arg.hotspot_id,
                "p2": arg.year,
                "p3": arg.species_code,
                "p4": arg.common_name,
                "p5": arg.scientific_name,
                "p6": arg.first_obs_date,
                "p7": arg.observer_name,
                "p8": arg.checklist_id,
            },
        )

    async def is_backfill_complete(
        self, *, hotspot_id: str, year: int
    ) -> Optional[int]:
        row = (
            await self._conn.execute(
                sqlalchemy.text(IS_BACKFILL_COMPLETE), {"p1": hotspot_id, "p2": year}
            )
        ).first()
        if row is None:
            return None
        return row[0]

    async def mark_backfill_complete(
        self, *, hotspot_id: str, year: int, species_count: int
    ) -> None:
        await self._conn.execute(
            sqlalchemy.text(MARK_BACKFILL_COMPLETE),
            {"p1": hotspot_id, "p2": year, "p3": species_count},
        )

    async def remove_all_time_species(
        self, *, hotspot_id: str, species_code: str
    ) -> None:
        await self._conn.execute(
            sqlalchemy.text(REMOVE_ALL_TIME_SPECIES),
            {"p1": hotspot_id, "p2": species_code},
        )

    async def remove_pending_provisional(
        self, *, hotspot_id: str, species_code: str, lifer_type: str
    ) -> None:
        await self._conn.execute(
            sqlalchemy.text(REMOVE_PENDING_PROVISIONAL),
            {"p1": hotspot_id, "p2": species_code, "p3": lifer_type},
        )

    async def remove_year_species(
        self, *, hotspot_id: str, year: int, species_code: str
    ) -> None:
        await self._conn.execute(
            sqlalchemy.text(REMOVE_YEAR_SPECIES),
            {"p1": hotspot_id, "p2": year, "p3": species_code},
        )
